name: SaLE
main: main.java.me.avankziar.sale.spigot.SaLE
version: 1
author: Avankziar
api-version: 1.17
description: A SignShop Plugin
softdepend: [InterfaceHub,Vault]
website: https://www.spigotmc.org/resources/shop-a-lot-extra.106371/