package main.java.me.avankziar.sale.spigot.objects;

public enum ClickFunctionType
{
	//Admin Button anzahl: 21
	//InfoItem
	//ADMINISTRATION_INFOITEM,
	//Toggelt An- & Verkauf
	ADMINISTRATION_TOGGLE_BUY,
	ADMINISTRATION_TOGGLE_SELL,
	//Neudefinierung des Items
	ADMINISTRATION_ITEM_CLEAR,
	//Einstellen des An- & Verkaufspreis
	ADMINISTRATION_NUMPAD_CANCEL,
	ADMINISTRATION_NUMPAD_COLON,
	ADMINISTRATION_NUMPAD_DECIMAL,
	ADMINISTRATION_NUMPAD_CLEAR,
	ADMINISTRATION_NUMPAD_0, //Setzt den KaufWertes auf die vorherige Zahl mit einem 0 am Ende. Bspw. 55 + 0 = 550
	ADMINISTRATION_NUMPAD_1,
	ADMINISTRATION_NUMPAD_2,
	ADMINISTRATION_NUMPAD_3,
	ADMINISTRATION_NUMPAD_4,
	ADMINISTRATION_NUMPAD_5,
	ADMINISTRATION_NUMPAD_6,
	ADMINISTRATION_NUMPAD_7,
	ADMINISTRATION_NUMPAD_8,
	ADMINISTRATION_NUMPAD_9,
	ADMINISTRATION_SETBUY_OPEN_NUMPAD,
	ADMINISTRATION_SETBUY_CLEAR, //Setzt den Preis auf 0 zurück.
	ADMINISTRATION_SETBUY_TAKEOVER, //Akzeptiert den eingetragen Betrag für den Wert
	ADMINISTRATION_SETSELL_OPEN_NUMPAD,
	ADMINISTRATION_SETSELL_CLEAR,
	ADMINISTRATION_SETSELL_TAKEOVER,
	//Erweiterung der Lagerräume, Zahl ist die Anzahl an Items, nicht Stacks
	ADMINISTRATION_ADDSTORAGE_1,
	ADMINISTRATION_ADDSTORAGE_16,
	ADMINISTRATION_ADDSTORAGE_64,
	ADMINISTRATION_ADDSTORAGE_576,
	//Angabe eines Konto
	ADMINISTRATION_SETACCOUNT_OPEN_NUMPAD,
	ADMINISTRATION_SETACCOUNT_DEFAULT, //Setzt es auf den MAIN acc, wenn nicht existiert, auf 0
	ADMINISTRATION_SETACCOUNT_TAKEOVER,
	//ShopStatistik
	ADMINISTRATION_OPEN_SHOPLOG,
	//ASH
	ADMINISTRATION_SETASH_OPEN_NUMPAD,
	ADMINISTRATION_SETASH_CLEAR,
	ADMINISTRATION_SETASH_TAKEOVER,
	//Ver- & Ankaufslimit
	ADMINISTRATION_SETPOSSIBLE_BUY_OPEN_NUMPAD,
	ADMINISTRATION_SETPOSSIBLE_BUY_CLEAR, //Setzt auf -1, aka deaktiviert
	ADMINISTRATION_SETPOSSIBLE_BUY_TAKEOVER,
	ADMINISTRATION_SETPOSSIBLE_SELL_OPEN_NUMPAD,
	ADMINISTRATION_SETPOSSIBLE_SELL_CLEAR,
	ADMINISTRATION_SETPOSSIBLE_SELL_TAKEOVER,
	//Discount
	ADMINISTRATION_SETDISCOUNT_CLEAR, //Setzt Start und Ende auf 0
	ADMINISTRATION_SETDISCOUNT_START_OPEN_NUMPAD,
	ADMINISTRATION_SETDISCOUNT_START_TAKEOVER,
	ADMINISTRATION_SETDISCOUNT_END_OPEN_NUMPAD,
	ADMINISTRATION_SETDISCOUNT_END_TAKEOVER,
	//Discount Ver- & Ankaufslimit
	ADMINISTRATION_SETDISCOUNTPOSSIBLE_BUY_OPEN_NUMPAD,
	ADMINISTRATION_SETDISCOUNTPOSSIBLE_BUY_CLEAR, //Setzt auf -1, aka deaktiviert
	ADMINISTRATION_SETDISCOUNTPOSSIBLE_BUY_TAKEOVER,
	ADMINISTRATION_SETDISCOUNTPOSSIBLE_SELL_OPEN_NUMPAD,
	ADMINISTRATION_SETDISCOUNTPOSSIBLE_SELL_CLEAR,
	ADMINISTRATION_SETDISCOUNTPOSSIBLE_SELL_TAKEOVER,
	//Discount Ver- & Ankaufspreis
	ADMINISTRATION_SETDISCOUNTBUY_OPEN_NUMPAD,
	ADMINISTRATION_SETDISCOUNTBUY_CLEAR, //Setzt den Preis auf 0 zurück.
	ADMINISTRATION_SETDISCOUNTBUY_TAKEOVER,
	ADMINISTRATION_SETDISCOUNTSELL_OPEN_NUMPAD,
	ADMINISTRATION_SETDISCOUNTSELL_CLEAR,
	ADMINISTRATION_SETDISCOUNTSELL_TAKEOVER,
	//Löschbutton
	ADMINISTRATION_DELETE_ALL,
	//OP SetUnlimited Toggle
	ADMINISTRATION_UNLIMITED_TOGGLE_BUY,
	ADMINISTRATION_UNLIMITED_TOGGLE_SELL,
	//SettingsLevel Change
	ADMINISTRATION_SETTINGSLEVEL_SETTO_BASE,
	ADMINISTRATION_SETTINGSLEVEL_SETTO_ADVANCED,
	ADMINISTRATION_SETTINGSLEVEL_SETTO_EXPERT,
	ADMINISTRATION_SETTINGSLEVEL_SETTO_MASTER,
	
	//ShopGui Button Anzahl: 15
	//SHOP_ITEMSTACK_VIEW, //Einfache Ansicht des Items wie es ist. Return beim Klick.
	//SHOP_ITEMSTACK_INFO, //Zeigt alle weitere Infos, Haltbarkeit, ItemFlags etc.
	SHOP_TOGGLE_SUBSCRIBE, //Toggelt ob man dem Shop abbonieren möchte.
	SHOP_BUY_1,
	SHOP_BUY_16,
	SHOP_BUY_32,
	SHOP_BUY_64,
	SHOP_BUY_576,
	SHOP_BUY_2304,
	SHOP_SELL_1,
	SHOP_SELL_16,
	SHOP_SELL_32,
	SHOP_SELL_64,
	SHOP_SELL_576,
	SHOP_SELL_2304
}
